name: Build and Release SystemMonitor

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'

env:
  BUILD_TYPE: Release
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git ${{ env.VCPKG_ROOT }}
        ${{ env.VCPKG_ROOT }}\bootstrap-vcpkg.bat
        ${{ env.VCPKG_ROOT }}\vcpkg integrate install

    - name: Install dependencies
      run: |
        ${{ env.VCPKG_ROOT }}\vcpkg install curl[ssl]:x64-windows-static
        
    - name: Build SystemMonitor
      run: |
        $env:VCPKG_ROOT="${{ env.VCPKG_ROOT }}"
        $env:VCPKG_TARGET="x64-windows-static"
        .\build.bat

    - name: Create Release Package
      run: |
        $version = "${{ github.event.inputs.version }}" 
        if (-not $version) { $version = $env:GITHUB_REF_NAME }
        
        $releaseDir = "SystemMonitor-$version"
        New-Item -ItemType Directory -Path $releaseDir -Force
        New-Item -ItemType Directory -Path "$releaseDir\config" -Force
        New-Item -ItemType Directory -Path "$releaseDir\docs" -Force
        
        # Copy files
        Copy-Item "bin\SystemMonitor.exe" "$releaseDir\"
        Copy-Item "config\SystemMonitor.cfg" "$releaseDir\config\SystemMonitor.cfg.template"
        Copy-Item "README.md" "$releaseDir\"
        if (Test-Path "docs") { Copy-Item "docs\*" "$releaseDir\docs\" -Recurse }
        
        # Create deployment guide
        @"
        # SystemMonitor $version - Deployment Package
        
        ## Installation
        1. Extract all files to your preferred directory
        2. Rename ``config\SystemMonitor.cfg.template`` to ``config\SystemMonitor.cfg``
        3. Configure your email settings in the config file
        4. Run: ``SystemMonitor.exe --display silence``
        
        ## Features
        - Enterprise system monitoring with TLS email alerts
        - Static linking - no external dependencies required
        - Multiple display modes for different use cases
        - Configurable thresholds and alert timing
        
        ## Requirements
        - Windows 10/11 or Windows Server 2016+
        - Visual C++ Redistributable 2022 (typically pre-installed)
        
        ## Support
        GitHub: https://github.com/dnguyenminh/SystemMonitor
        "@ | Out-File -FilePath "$releaseDir\DEPLOYMENT_README.md" -Encoding UTF8
        
        # Create ZIP archive
        Compress-Archive -Path "$releaseDir\*" -DestinationPath "SystemMonitor-$version.zip" -Force
        
        echo "RELEASE_FILE=SystemMonitor-$version.zip" >> $env:GITHUB_ENV
        echo "RELEASE_DIR=$releaseDir" >> $env:GITHUB_ENV

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SystemMonitor-Release
        path: ${{ env.RELEASE_FILE }}

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.RELEASE_FILE }}
        name: SystemMonitor ${{ env.GITHUB_REF_NAME }}
        body: |
          ## SystemMonitor ${{ env.GITHUB_REF_NAME }}
          
          ### 🚀 Features
          - Real-time system monitoring (CPU, RAM, Disk)
          - TLS-encrypted email alerts via Gmail SMTP
          - Multiple display modes (line, top, compact, silence)
          - Static linking for easy deployment
          - Configurable thresholds and alert timing
          
          ### 📦 Deployment
          - **Self-contained executable** - No external dependencies
          - **Windows 10/11 compatible** - Server 2016+ supported
          - **Enterprise ready** - Professional monitoring solution
          
          ### 📥 Installation
          1. Download and extract `SystemMonitor-${{ env.GITHUB_REF_NAME }}.zip`
          2. Configure `config/SystemMonitor.cfg.template` → `config/SystemMonitor.cfg`
          3. Run: `SystemMonitor.exe --display silence`
          
          ### 🔧 Configuration
          - Set monitoring thresholds (CPU/RAM/Disk %)
          - Configure Gmail SMTP with App Password
          - Customize alert duration and cooldown periods
          
          Built with: Visual Studio 2022, vcpkg, libcurl with TLS support
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
